name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
      
    - name: Run Super-Linter
      uses: github/super-linter@v4
      env:
        VALIDATE_PYTHON: true   # Enables Python linting
        VALIDATE_HTML: true     # Enables HTML linting
        VALIDATE_JAVASCRIPT: true # Enables JavaScript linting
        DEFAULT_BRANCH: main    # Set default branch for linting checks
